[package]
name = "samplesheet"
version = "0.1.2"
edition = "2024"
publish = false

[dependencies]
anyhow = "1.0.97"
camino = { version = "1.1.9", features = ["serde1"] }
clap = { version = "4.5.32", features = ["derive", "env", "wrap_help"] }
csv = "1"
itertools = "0.14.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.140"
toml = "0.8.20"
