[samplesheet.species_reference_path]
"Homo sapiens" = { "cellranger count" = "/sc/service/pipelines/references/10x-rna/refdata-gex-GRCh38-2020-A", "cellranger multi" = "/sc/service/pipelines/references/10x-rna/refdata-gex-GRCh38-2020-A" }
"Mus musculus" = { "cellranger count" = "/sc/service/pipelines/references/10x-rna/refdata-gex-mm10-2020-A", "cellranger multi" = "/sc/service/pipelines/references/10x-rna/refdata-gex-mm10-2020-A" }

[samplesheet.chemistry_program]
"Multiplex Flex Gene Expression (Next GEM)" = ["cellranger", "7.1.0", "multi"]
"Multiplex Flex Gene Expression (GEM-X)" = ["cellranger", "9.0.1", "multi"]
"Single Cell 3' v4 (polyA)" = ["cellranger", "9.0.1", "count"]
"Single Cell 3' v4 (polyA) OCM" = ["cellranger", "9.0.1", "multi"]

[samplesheet.species_probe_set]
"Homo sapiens" = "1.0/Chromium_Human_Transcriptome_Probe_Set_v1.0.1_GRCh38-2020-A.csv"
"Mus musculus" = "1.0/Chromium_Mouse_Transcriptome_Probe_Set_v1.0.1_mm10-2020-A.csv"

[xenium]
spreadsheet_spec = { id = "", range = "'Bioinformatics2'!A2:D1000", slide_id_col_idx = 0, slide_name_col_idx = 1, run_id_col_idx = 2, lab_name_col_idx = 3 }
google_sheets_api_key = ""

[xenium.staging_dir_spec]
root = "/sc/service/staging"

[xenium.staging_dir_spec.lab_dirs]
"Adam Williams Lab" = "adam_williams"
"Akiko Nishiyama Lab" = "akiko_nishiyama"
"Alexander Jackson Lab" = "alexander_jackson"
"Alice Burghard Lab" = "alice_burghard"
"Andy Greene Lab" = "andy_greene"
"Annabelle Rodriguez-Oquendo Lab" = "annabelle_rodriguez-oquendo"
"Anne Delany Lab" = "anne_delany"
"Beiyan Zhou Lab" = "beiyan_zhou"
"Blanka Rogina Lab" = "blanka_rogina"
"Bob Braun Lab" = "bob_braun"
"Byoung-Il Bae Lab" = "byoung-il_bae"
"CATch" = "project_catch"
"Catherine Kaczorowski Lab" = "catherine_kaczorowski"
"Cato Laurencin Lab" = "cato_laurencin"
"Ching Lau Lab" = "ching_lau"
"Chris Baker Lab" = "chris_baker"
"Craig Nelson Lab" = "craig_nelson"
"Dan Skelly Lab" = "dan_skelly"
"Daniel Bolnick Lab" = "daniel_bolnick"
"Daniel Mulkey Lab" = "daniel_mulkey"
"Dashzeveg Bayarsaihan Lab" = "dashzeveg_bayarsaihan"
"Dave Serreze Lab" = "dave_serreze"
"David Tuveson Lab" = "david_tuveson"
"Dong Zhou Lab" = "dong_zhou"
"Duygu Ucar Lab" = "duygu_ucar"
"Ed Liu Lab" = "ed_liu"
"Elise Courtois Lab" = "elise_courtois"
"Elissa Chesler Lab" = "elissa_chesler"
"Eric Wang Lab" = "eric_wang"
"Ewelina Bolcun-Filas Lab" = "ewelina_bolcun-filas"
"Feliks Trakhtenberg Lab" = "feliks_trakhtenberg"
"Frederick Varn Lab" = "frederick_varn"
"Gareth Howell Lab" = "gareth_howell"
"Gary Ren Lab" = "gary_ren"
"Greg Cox Lab" = "greg_cox"
"Hala Saneh Lab" = "hala_saneh"
"HuBMAP" = "project_hubmap"
"I-Ping Chen Lab" = "i-ping_chen"
"INDI" = "project_indi-opensci"
"Ivo Kalajzic Lab" = "ivo_kalajzic"
"JAX-Sen TMC" = "project_jaxsen-tmc"
"Jacques Banchereau Lab" = "jacques_banchereau"
"Jaime Imitola Lab" = "jaime_imitola"
"James Li Lab" = "james_li"
"Jason Bubier Lab" = "jason_bubier"
"Jeff Chuang Lab" = "jeff_chuang"
"Jenna Bartley Lab" = "jenna_bartley"
"Jennifer Trowbridge Lab" = "jennifer_trowbridge"
"Jill Rubinstein Lab" = "jill_rubinstein"
"Jmcrs Pali-Kaur Lab" = "jmcrs_pali-kaur"
"John Graham Lab" = "john_graham"
"Joseph Lorenzo Lab" = "joseph_lorenzo"
"Julia Oh Lab" = "julia_oh"
"Justin Cotney Lab" = "justin_cotney"
"KAPP-Sen TMC" = "project_kappsen-tmc"
"Karolina Palucka Lab" = "karolina_palucka"
"Kepeng Wang Lab" = "kepeng_wang"
"Kristen Oconnell Lab" = "kristen_oconnell"
"Kshitiz Lab" = "kshitiz"
"Laurinda Jaffe Lab" = "laurinda_jaffe"
"Lenny Shultz Lab" = "lenny_shultz"
"Liisa Kuhn Lab" = "liisa_kuhn"
"Lucas Chang Lab" = "lucas_chang"
"Luciano Martelotto Lab" = "luciano_martelotto"
"Martin Pera Lab" = "martin_pera"
"Michael Samuels Lab" = "michael_samuels"
"Michael Stitzel Lab" = "michael_stitzel"
"Ming Xu Lab" = "ming_xu"
"MorPhiC" = "project_morphic"
"Nadia Rosenthal Lab" = "nadia_rosenthal"
"Olga Anczukow Lab" = "olga_anczukow"
"Paul Robson Lab" = "paul_robson"
"Penghua Wang Lab" = "penghua_wang"
"Phillip Smith Lab" = "phillip_smith"
"Phillip West Lab" = "phillip_west"
"Rachel Oneill Lab" = "rachel_oneill"
"Rafiou Agoro Lab" = "rafiou_agoro"
"Rahul Kanadia Lab" = "rahul_kanadia"
"Raj Verma Lab" = "raj_verma"
"Rashmi Bansal Lab" = "rashmi_bansal"
"Riqiang Yan Lab" = "riqiang_yan"
"Roel Verhaak Lab" = "roel_verhaak"
"Rosa Guzzo Lab" = "rosa_guzzo"
"Royce Mohan Lab" = "royce_mohan"
"Service Single-Cell-Biology Lab" = "service_single-cell-biology"
"Sheng Li Lab" = "sheng_li"
"Shengdong Ke Lab" = "shengdong_ke"
"Silke Paust Lab" = "silke_paust"
"Steve Murray Lab" = "steve_murray"
"Sumit Yadav Lab" = "sumit_yadav"
"Testing Lab" = "testing"
"The Cancer Cube" = "project_the-cancer-cube"
"The Cube" = "project_the-cube"
"The Cube Lab" = "the_cube"
"To Delete Lab" = "to_delete"
"Travis Hinson Lab" = "travis_hinson"
"Yijun Ruan Lab" = "yijun_ruan"
"Zhichao Fan Lab" = "zhichao_fan"
